#pragma once

#define IARA_MOUSE_BUTTON_1         0
#define IARA_MOUSE_BUTTON_2         1
#define IARA_MOUSE_BUTTON_3         2
#define IARA_MOUSE_BUTTON_4         3
#define IARA_MOUSE_BUTTON_5         4
#define IARA_MOUSE_BUTTON_6         5
#define IARA_MOUSE_BUTTON_7         6
#define IARA_MOUSE_BUTTON_8         7
#define IARA_MOUSE_BUTTON_LAST      IARA_MOUSE_BUTTON_8
#define IARA_MOUSE_BUTTON_LEFT      IARA_MOUSE_BUTTON_1
#define IARA_MOUSE_BUTTON_RIGHT     IARA_MOUSE_BUTTON_2
#define IARA_MOUSE_BUTTON_MIDDLE    IARA_MOUSE_BUTTON_3